# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# Default values for slim-control-plane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "ghcr.io/agntcy/slim/control-plane"
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "slim-control"

config:
  northbound:
    httpHost: 0.0.0.0
    httpPort: "{{ .Values.service.north.port }}"

  southbound:
    httpHost: 0.0.0.0
    httpPort: "{{ .Values.service.south.port }}"
    # tls:
    #   useSpiffe: true
    # spire:
    #   socketPath: "unix:///run/spire/agent-sockets/api.sock"

  logging:
    level: DEBUG

spire:
  enabled: false
  trustedDomains:  
  - spiffe://cluster-a.example
  - spiffe://cluster-b.example

ingressSouth:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600s"
    nginx.ingress.kubernetes.io/proxy-stream-timeout: "3600s"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_socket_keepalive on;
      keepalive_timeout 3600s;
      grpc_read_timeout 3600s;
      grpc_send_timeout 3600s;
      client_header_timeout 60m;
      client_body_timeout 60m;
      http2_max_requests 10000;
      http2_max_concurrent_streams 128; 
  hosts:
    - host: slim-control.cluster-a.example
      paths:
        - path: /
          pathType: Prefix
          port: 50052
  tls:
    - secretName: slim-control-tls
      hosts:
        - slim-control.cluster-a.example

service:
  type: ClusterIP
  south:
    port: 50052
  north:
    port: 50051
